In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('2016_projects_medIncome.csv')

In [3]:
df

,Unnamed: 0,_projectid,school_latitude,school_longitude,school_city,school_state,school_zip,school_metro,school_charter,school_magnet,...,donation_included_optional_support,payment_method,payment_included_acct_credit,payment_included_campaign_gift_card,payment_included_web_purchased_gift_card,payment_was_promo_matched,is_teacher_referred,for_honoree,thank_you_packet_mailed,school_median_household_income
0,0,873d0f24179f92033a67c97b09c2b165,40.716050,-73.990920,New York City,NY,10002.0,0,0,0,...,t,no_cash_received,f,t,f,f,f,f,f,33218.0
1,1,873d0f24179f92033a67c97b09c2b165,40.716050,-73.990920,New York City,NY,10002.0,0,0,0,...,f,check,f,f,f,f,f,f,t,33218.0
2,3,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,f,creditcard,f,f,f,f,f,f,f,23452.0
3,4,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,t,creditcard,f,f,f,f,f,f,t,23452.0
4,5,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,t,creditcard,f,f,f,f,f,f,f,23452.0
5,6,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,t,creditcard,f,f,f,f,f,f,f,23452.0
6,7,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,f,creditcard,f,f,f,f,f,f,f,23452.0
7,8,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,t,creditcard,f,f,f,f,f,f,f,23452.0
8,9,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,t,creditcard,f,f,f,f,f,f,f,23452.0
9,10,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,t,creditcard,f,f,f,f,f,f,f,23452.0
10,11,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,t,creditcard,f,f,f,f,f,t,f,23452.0
11,14,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,t,creditcard,f,f,f,f,f,f,t,23452.0
12,15,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,f,creditcard,f,f,f,f,f,f,f,23452.0
13,16,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,f,creditcard,f,f,f,f,f,f,f,23452.0
14,17,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,t,creditcard,f,f,f,f,f,f,f,23452.0
15,18,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,f,creditcard,f,f,f,f,f,t,f,23452.0
16,19,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,t,creditcard,f,f,f,f,f,f,f,23452.0
17,20,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,f,creditcard,f,f,f,f,f,f,f,23452.0
18,21,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,t,creditcard,f,f,f,f,f,f,t,23452.0
19,23,e60d22af70d53e2c76a225a61618f233,41.865633,-87.676044,Chicago,IL,60608.0,0,0,1,...,t,creditcard,f,f,f,f,f,f,t,35336.0
20,24,e60d22af70d53e2c76a225a61618f233,41.865633,-87.676044,Chicago,IL,60608.0,0,0,1,...,f,no_cash_received,f,f,t,f,f,f,f,35336.0
21,25,a037be87faf4a4d6b98715b1fe9a2ef2,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,t,no_cash_received,f,t,f,f,f,f,f,23452.0
22,26,a037be87faf4a4d6b98715b1fe9a2ef2,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,...,f,check,f,f,f,f,f,f,t,23452.0
23,27,0f6b9e2694706bc7565f2bd6a32004d3,33.980891,-118.368531,Inglewood,CA,90302.0,2,0,0,...,t,check,f,f,f,f,f,f,t,43042.0
24,28,0f6b9e2694706bc7565f2bd6a32004d3,33.980891,-118.368531,Inglewood,CA,90302.0,2,0,0,...,t,check,f,f,f,f,f,f,t,43042.0
25,29,348bf4d3de47f629995da6f4ea51344b,41.865633,-87.676044,Chicago,IL,60608.0,0,0,1,...,t,no_cash_received,f,t,f,f,f,f,f,35336.0
26,30,348bf4d3de47f629995da6f4ea51344b,41.865633,-87.676044,Chicago,IL,60608.0,0,0,1,...,t,creditcard,f,f,f,f,f,t,t,35336.0
27,31,348bf4d3de47f629995da6f4ea51344b,41.865633,-87.676044,Chicago,IL,60608.0,0,0,1,...,t,no_cash_received,f,t,f,f,f,f,f,35336.0
28,32,348bf4d3de47f629995da6f4ea51344b,41.865633,-87.676044,Chicago,IL,60608.0,0,0,1,...,t,no_cash_received,f,t,f,f,f,f,f,35336.0
29,33,f885a70d5f1c5b4602de226a05d503e1,33.980891,-118.368531,Inglewood,CA,90302.0,2,0,0,...,t,check,f,f,f,f,f,t,f,43042.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312362,1092956,2515a011a1ec1524ab55b881ec52dd49,37.813077,-122.286845,Oakland,CA,94607.0,0,0,0,...,t,no_cash_received,f,f,f,f,f,f,f,32856.0
312363,1092957,2f0169df6160e66eb7381a65e1fb2f05,30.504344,-90.924336,Denham Springs,LA,70726.0,2,0,0,...,f,no_cash_received,t,f,f,f,f,f,f,57246.0
312364,1092959,3095d51e63ef643ce0082e7fdbe0e28a,40.095967,-75.057778,Philadelphia,PA,19115.0,0,0,0,...,t,no_cash_received,f,f,f,f,t,f,f,45799.0
312365,1092960,3ac63394f734f36294f65581ea36dfca,40.687286,-73.988217,New York City,NY,11201.0,0,0,1,...,f,no_cash_received,f,f,t,f,t,f,f,95369.0
312366,1092961,3ac63394f734f36294f65581ea36dfca,40.687286,-73.988217,New York City,NY,11201.0,0,0,1,...,f,paypal,f,f,f,f,t,f,f,95369.0
312367,1092962,f52bf9135cb9400204a46c4ea436fd48,30.486743,-90.943650,Denham Springs,LA,70726.0,2,0,0,...,f,no_cash_received,t,f,f,f,f,f,f,57246.0
312368,1092963,42431896ef370a7995405b1c8ae811c6,30.504344,-90.924336,Denham Springs,LA,70726.0,2,0,0,...,f,no_cash_received,t,f,f,f,f,f,f,57246.0
312369,1092964,f86efe3a1190b99e1e686806b4ad1a63,40.053138,-75.069680,Philadelphia,PA,19111.0,0,0,0,...,t,no_cash_received,f,f,f,f,t,f,f,44123.0
312370,1092967,f86efe3a1190b99e1e686806b4ad1a63,40.053138,-75.069680,Philadelphia,PA,19111.0,0,0,0,...,t,no_cash_received,f,f,f,f,f,f,f,44123.0
312371,1092969,453783b5d5daf31261112551be3bd1bc,40.053138,-75.069680,Philadelphia,PA,19111.0,0,0,0,...,t,no_cash_received,f,t,f,f,t,f,f,44123.0
312372,1092972,453783b5d5daf31261112551be3bd1bc,40.053138,-75.069680,Philadelphia,PA,19111.0,0,0,0,...,t,no_cash_received,f,t,f,f,t,f,f,44123.0
312373,1092975,453783b5d5daf31261112551be3bd1bc,40.053138,-75.069680,Philadelphia,PA,19111.0,0,0,0,...,t,no_cash_received,f,t,f,f,t,f,f,44123.0
312374,1092977,453783b5d5daf31261112551be3bd1bc,40.053138,-75.069680,Philadelphia,PA,19111.0,0,0,0,...,t,no_cash_received,f,t,f,f,t,f,f,44123.0
312375,1092979,453783b5d5daf31261112551be3bd1bc,40.053138,-75.069680,Philadelphia,PA,19111.0,0,0,0,...,t,no_cash_received,f,t,f,f,t,f,f,44123.0
312376,1092981,453783b5d5daf31261112551be3bd1bc,40.053138,-75.069680,Philadelphia,PA,19111.0,0,0,0,...,t,no_cash_received,f,t,f,f,t,f,f,44123.0
312377,1092982,453783b5d5daf31261112551be3bd1bc,40.053138,-75.069680,Philadelphia,PA,19111.0,0,0,0,...,t,no_cash_received,f,t,f,f,t,f,f,44123.0
312378,1092983,453783b5d5daf31261112551be3bd1bc,40.053138,-75.069680,Philadelphia,PA,19111.0,0,0,0,...,t,no_cash_received,f,t,f,f,f,f,f,44123.0
312379,1092985,453783b5d5daf31261112551be3bd1bc,40.053138,-75.069680,Philadelphia,PA,19111.0,0,0,0,...,t,no_cash_received,f,t,f,f,f,f,f,44123.0
312380,1092986,453783b5d5daf31261112551be3bd1bc,40.053138,-75.069680,Philadelphia,PA,19111.0,0,0,0,...,t,creditcard,f,f,f,f,t,f,f,44123.0
312381,1092987,453783b5d5daf31261112551be3bd1bc,40.053138,-75.069680,Philadelphia,PA,19111.0,0,0,0,...,t,no_cash_received,f,t,f,f,f,f,f,44123.0
312382,1092988,4721e67478389fafcd7d9348c8b8cb31,30.562881,-91.042206,Baton Rouge,LA,70818.0,2,0,0,...,f,no_cash_received,t,f,f,f,f,f,f,65948.0
312383,1093002,51e50a783a2e8579319d23f92e704969,42.305195,-85.613177,Kalamazoo,MI,49006.0,2,0,0,...,f,paypal,f,f,f,f,f,f,f,32016.0
312384,1093005,70b9c285b86de60e0320ab56bf2fb1d2,30.272251,-90.904368,Gonzales,LA,70737.0,2,0,0,...,f,no_cash_received,t,f,f,f,f,f,f,60590.0
312385,1093010,8012285c8f91be922601f13067a599ef,34.838573,-82.321510,Greenville,SC,29607.0,0,0,1,...,t,no_cash_received,f,f,t,f,t,f,f,48809.0
312386,1093013,86a09a7971a693e3352405a2a3320438,40.048832,-75.076876,Philadelphia,PA,19111.0,0,0,0,...,t,no_cash_received,f,t,f,f,t,f,f,44123.0
312387,1093014,86a09a7971a693e3352405a2a3320438,40.048832,-75.076876,Philadelphia,PA,19111.0,0,0,0,...,t,no_cash_received,f,t,f,f,t,f,f,44123.0
312388,1093015,889c78705ec0727f03735d03c005c6ff,30.461050,-91.072086,Baton Rouge,LA,70815.0,0,0,0,...,f,no_cash_received,t,f,f,f,f,f,f,47979.0
312389,1093016,8a6a3e778e722c940c0d5b70d4b57552,45.516563,-122.486771,Portland,OR,97233.0,0,0,0,...,t,creditcard,f,f,f,f,f,f,f,35970.0
312390,1093018,a89c378a19f5dcd69b7ca8e97c6bf81e,36.052131,-79.818365,Greensboro,NC,27403.0,0,0,0,...,t,creditcard,f,f,f,f,f,f,f,36664.0
312391,1093020,aa2d6beaeaec7bc4d2e2a63fa92bbeeb,30.392318,-90.767048,Livingston,LA,70754.0,1,0,0,...,f,no_cash_received,t,f,f,f,f,f,f,55758.0

In [4]:
df.columns

Index(['Unnamed: 0', '_projectid', 'school_latitude', 'school_longitude',
       'school_city', 'school_state', 'school_zip', 'school_metro',
       'school_charter', 'school_magnet', 'school_year_round', 'school_nlns',
       'school_kipp', 'school_charter_ready_promise', 'teacher_prefix',
       'teacher_teach_for_america', 'teacher_ny_teaching_fellow',
       'primary_focus_subject', 'primary_focus_area', 'resource_type',
       'poverty_level', 'grade_level',
       'total_price_excluding_optional_support',
       'total_price_including_optional_support', 'students_reached',
       'total_donations', 'num_donors', 'eligible_double_your_impact_match',
       'eligible_almost_home_match', 'funding_status', 'date_posted',
       'date_expiration', 'timespan', 'month_posted', '_donationid',
       '_donor_acctid', 'donor_city', 'donor_state', 'donor_zip',
       'is_teacher_acct', 'donation_timestamp', 'donation_to_project',
       'donation_optional_support', 'donation_total',
       'donation_included_optional_support', 'payment_method',
       'payment_included_acct_credit', 'payment_included_campaign_gift_card',
       'payment_included_web_purchased_gift_card', 'payment_was_promo_matched',
       'is_teacher_referred', 'for_honoree', 'thank_you_packet_mailed',
       'school_median_household_income'],
      dtype='object')

In [5]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [6]:
#df.drop([''],axis=1,inplace=True)

In [7]:
df.head()

,_projectid,school_latitude,school_longitude,school_city,school_state,school_zip,school_metro,school_charter,school_magnet,school_year_round,...,donation_included_optional_support,payment_method,payment_included_acct_credit,payment_included_campaign_gift_card,payment_included_web_purchased_gift_card,payment_was_promo_matched,is_teacher_referred,for_honoree,thank_you_packet_mailed,school_median_household_income
0,873d0f24179f92033a67c97b09c2b165,40.716050,-73.990920,New York City,NY,10002.0,0,0,0,0,...,t,no_cash_received,f,t,f,f,f,f,f,33218.0
1,873d0f24179f92033a67c97b09c2b165,40.716050,-73.990920,New York City,NY,10002.0,0,0,0,0,...,f,check,f,f,f,f,f,f,t,33218.0
2,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,0,...,f,creditcard,f,f,f,f,f,f,f,23452.0
3,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,0,...,t,creditcard,f,f,f,f,f,f,t,23452.0
4,39cc140c93514b4cad8f6df0da42e24d,40.832143,-73.917686,New York City,NY,10456.0,0,0,0,0,...,t,creditcard,f,f,f,f,f,f,f,23452.0

In [8]:
import geopy.distance as gp

In [9]:
coords_1 = [df['school_latitude'][0],df['school_longitude'][0]]
coords_2 = (30, -80)
print(gp.geodesic(coords_1, coords_2).km)
print(gp.distance(coords_1, coords_2).mi)

1307.4993690999747
812.4424418272132

In [10]:
import time

In [43]:
from uszipcode import SearchEngine
search_zip = SearchEngine(simple_zipcode=True)

In [47]:
search_zip.by_city_and_state('Los Angeles','CA')[0].to_dict()

{'zipcode': '90001',
 'zipcode_type': 'Standard',
 'major_city': 'Los Angeles',
 'post_office_city': 'Los Angeles, CA',
 'common_city_list': ['Los Angeles', 'Firestone Park', 'Firestone Pk'],
 'county': 'Los Angeles County',
 'state': 'CA',
 'lat': 33.97,
 'lng': -118.25,
 'timezone': 'Pacific',
 'radius_in_miles': 1.0,
 'area_code_list': ['323'],
 'population': 57110,
 'population_density': 16306.0,
 'land_area_in_sqmi': 3.5,
 'water_area_in_sqmi': 0.0,
 'housing_units': 13788,
 'occupied_housing_units': 12971,
 'median_home_value': 249600,
 'median_household_income': 35097,
 'bounds_west': -118.265185,
 'bounds_east': -118.230013,
 'bounds_north': 33.989498,
 'bounds_south': 33.958518}

In [ ]:
search_zip.by_city_and_state('Los Angeles','CA')[0].to_dict()

In [60]:
def Average(lst):
    if len(lst) == 0:
        return 'NaN'
    else:
        return sum(lst) / len(lst) 

def getDistance(df):
    school_coords = [df['school_latitude'],df['school_longitude']]
    donor_zip = search_zip.by_city_and_state(df['donor_city'], df['donor_state'])
    lats = []
    lngs = []
    med_income = []
    pop = []
    pop_dens = []
    housing = []
    housing_occu = []
    med_home_val = []
    for c in donor_zip:
        z_dict = c.to_dict()
        if z_dict.get('lat') is None or z_dict.get('lng') is None or z_dict.get('median_household_income') is None or z_dict.get('population') is None or z_dict.get('population_density') is None or z_dict.get('housing_units') is None or z_dict.get('occupied_housing_units') is None or z_dict.get('median_home_value') is None:
            next
        else:
            lats.append(z_dict.get('lat'))
            lngs.append(z_dict.get('lng'))
            med_income.append(z_dict.get('median_household_income'))
            pop.append(z_dict.get('population'))
            pop_dens.append(z_dict.get('population_density'))
            housing.append(z_dict.get('housing_units'))
            housing_occu.append(z_dict.get('occupied_housing_units'))
            med_home_val.append(z_dict.get('median_home_value'))
    donor_coords = [Average(lats),Average(lngs)]
    if donor_coords[0] == 'NaN' or donor_coords[1] == 'NaN':
        return ['NaN', Average(med_income), Average(pop), Average(pop_dens), Average(housing), Average(housing_occu), Average(med_home_val)]
    else:
        return [gp.distance(school_coords, donor_coords).mi,Average(med_income),Average(pop), Average(pop_dens), Average(housing), Average(housing_occu), Average(med_home_val)]

In [33]:
newcoltest = df[0:10].apply(getDistance, axis=1)

In [61]:
newnewtest = df[0:10].apply(getDistance, axis=1)

In [74]:
newnewtest

0    [0.5446250157801078, 92282.4, 33752.0, 65257.4...
1    [0.5446250157801078, 92282.4, 33752.0, 65257.4...
2    [1098.6216617815048, 25038.25, 34003.75, 12696...
3    [8.775526881698456, 92282.4, 33752.0, 65257.4,...
4    [176.4987764156293, 40529.8, 26652.2, 9242.8, ...
5    [298.94138392052827, 47982.0, 14870.0, 295.0, ...
6    [8.775526881698456, 92282.4, 33752.0, 65257.4,...
7    [2468.5183738730652, 81953.8, 18408.6, 10441.0...
8    [204.534686793873, 82801.2, 35990.8, 4972.4, 1...
9    [434.9075695391546, 67713.5, 27286.5, 456.5, 1...
dtype: object

In [ ]:
#df['donor_distance_from_school'] = df['school_zip'].apply(getMedIncome)

start = time.time()
#newcol = df.apply(getDistance, axis=1)
end = time.time()

WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '-----']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: ', --']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']

WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']

WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']
WARNING:root:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '*']

In [ ]:
newcol

In [ ]:
print(end-start)

In [34]:
newcoltest.apply(lambda x: x[0])

0       0.544625
1       0.544625
2    1098.621662
3       8.775527
4     176.498776
5     298.941384
6       8.775527
7    2468.518374
8     204.534687
9     434.907570
dtype: float64

In [35]:
newcoltest.apply(lambda x: x[1])

0    92282.40
1    92282.40
2    25038.25
3    92282.40
4    40529.80
5    47982.00
6    92282.40
7    81953.80
8    82801.20
9    67713.50
dtype: float64

In [50]:
df[['donor_city', 'donor_state']][12344:12364]

             donor_city donor_state
12344     Oklahoma City          OK
12345           Kahului          HI
12346          Ligonier          PA
12347       Springfield          IL
12348           Detroit          MI
12349     San Francisco          CA
12350  Huntington Beach          CA
12351  Huntington Beach          CA
12352  Huntington Beach          CA
12353      Ventnor City          NJ
12354         Manalapan          NJ
12355      Hillsborough          NJ
12356          New York          NY
12357       Nevada City          CA
12358         Kentfield          CA
12359         Sausalito          CA
12360          La Jolla          CA
12361          La Jolla          CA
12362        Springdale          AR
12363           Midland          GA

In [55]:
search_zip.by_city_and_state('San Francisco','CA')

[SimpleZipcode(zipcode='94101', zipcode_type='Standard', major_city='San Francisco', post_office_city=None, common_city_list=['San Francisco'], county='San Francisco County', state='CA', lat=None, lng=None, timezone=None, radius_in_miles=None, area_code_list=['415'], population=None, population_density=None, land_area_in_sqmi=None, water_area_in_sqmi=None, housing_units=None, occupied_housing_units=None, median_home_value=None, median_household_income=None, bounds_west=None, bounds_east=None, bounds_north=None, bounds_south=None),
 SimpleZipcode(zipcode='94102', zipcode_type='Standard', major_city='San Francisco', post_office_city='San Francisco, CA', common_city_list=['San Francisco'], county='San Francisco County', state='CA', lat=37.78, lng=-122.42, timezone='Pacific', radius_in_miles=0.9090909090909091, area_code_list=['415', '510'], population=31176, population_density=46472.0, land_area_in_sqmi=0.67, water_area_in_sqmi=0.0, housing_units=18758, occupied_housing_units=16844, median_home_value=574100, median_household_income=22517, bounds_west=-122.42992, bounds_east=-122.404583, bounds_north=37.789226, bounds_south=37.769441),
 SimpleZipcode(zipcode='94103', zipcode_type='Standard', major_city='San Francisco', post_office_city='San Francisco, CA', common_city_list=['San Francisco'], county='San Francisco County', state='CA', lat=37.78, lng=-122.41, timezone='Pacific', radius_in_miles=1.0, area_code_list=['510', '650', '415'], population=27170, population_density=20036.0, land_area_in_sqmi=1.36, water_area_in_sqmi=0.0, housing_units=14778, occupied_housing_units=13098, median_home_value=628000, median_household_income=43364, bounds_west=-122.427704, bounds_east=-122.397812, bounds_north=37.78805, bounds_south=37.763561),
 SimpleZipcode(zipcode='94104', zipcode_type='Standard', major_city='San Francisco', post_office_city='San Francisco, CA', common_city_list=['San Francisco'], county='San Francisco County', state='CA', lat=37.791, lng=-122.402, timezone='Pacific', radius_in_miles=0.2840909090909091, area_code_list=['415', '510', '650'], population=406, population_density=5232.0, land_area_in_sqmi=0.08, water_area_in_sqmi=0.0, housing_units=368, occupied_housing_units=207, median_home_value=1000001, median_household_income=48750, bounds_west=-122.404613, bounds_east=-122.399149, bounds_north=37.793987, bounds_south=37.787642),
 SimpleZipcode(zipcode='94105', zipcode_type='Standard', major_city='San Francisco', post_office_city='San Francisco, CA', common_city_list=['San Francisco'], county='San Francisco County', state='CA', lat=37.789, lng=-122.395, timezone='Pacific', radius_in_miles=0.625, area_code_list=['510', '415', '650'], population=5846, population_density=15826.0, land_area_in_sqmi=0.37, water_area_in_sqmi=0.08, housing_units=4601, occupied_housing_units=3586, median_home_value=740900, median_household_income=163949, bounds_west=-122.403431, bounds_east=-122.385181, bounds_north=37.796628, bounds_south=37.784205)]